const ERROR_CODES = {

    /**
     * General
     */
    INVALID_PARAMS: 'INVALID_PARAMS',

    /**
     * Patient
     */
    PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',

    /**
     * Appointments
     */
    APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
    APPOINTMENT_NOT_FREE: 'APPOINTMENT_NOT_FREE',
    CANNOT_CANCEL_APPOINTMENT: 'CANNOT_CANCEL_APPOINTMENT',
}

export default ERROR_CODES;